### PR TITLE
Bring sort order to shortcode, add max sponsors

### PR DESCRIPTION
**Pull request by peppermintpig**
- add the possibility to specify the max number of sponsors to show in the widget or the shortcode
- bring the random sort order to the shortcode

Hello

Found your plugin, was doing almost all stuff I needed. Except the max items to display, which I added in develop branch

Please note that my PHP skills are limited, so please double check. Also the way php handles the i18n aspects are unknown to me, so that it has been omitted

In the hope it can be useful

CU

Christophe

### CODE REVIEW

**Comment by janhenckens** [comment]
[WP Sponsors - review and release #9](https://trello.com/c/QcbBKX62/89-wp-sponsors-review-and-release-9)

**Comment by janhenckens** [comment]
Hey! Thanks for the suggestions and for the PR!
I'll have a look at the translations and the max option and will merge when it looks good :)

**Comment by janhenckens** [comment]
Hey again!
Liking these additions, but the finish needs some work. I'll merge your PR and add some tweaks of my own. 

You can expect this to be release somewhere this week!
Thanks again,
Jan

**Comment by peppermintpig** [comment]
Thanks

Sorry, I just started using Wordpress, PHP and Git. Seems I still have a
lot to learn ;-)

Happy to see my small contribution can help other people

Salutations / groetjes from Brussels

Christophe

**Comment by janhenckens** [comment]
Hey Christophe, would you be willing to help me out with French translations for the plugin? you can also email me at jan@studioespresso.co :)

**Comment by peppermintpig** [comment]
Hello Jan

I can try at least!

I understand the structure of the file *wp-sponsors-nl_BE.po *for instance
and can translate it into fr_BE and fr_FR. I guess you will then be able to
generate the '.mo'.

I'll do it this evening, wanted to work in the garden this afternoon

CU

Christophe

**Comment by peppermintpig** [comment]
Hello Jan

I created a PR for the French translation

I tried to keep the Wordpress spirit (I checked with a French install), yet
match your labels as close as possible

Note that I really think you can make this an fr-FR translation as well.
The only things I would extra translate are those English words for
'widget' and 'shortcode'. French people tend to translate every English
word. But at the end it confuses more than it helps, so that I think they
can be kept as-is

Have a nice evening

Christophe

PS Sorry don't know what PHP uses as translation helper. I just edited the
message file, I hope you can generate .mo files from this

**Pull request merged**
